CREATE TABLE usuarios (
  id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_usuario VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha_hash VARCHAR(255) NOT NULL,
  data_registro TIMESTAMP NOT NULL,
  ultimo_login TIMESTAMP
);

CREATE TABLE desenvolvedoras (
  id_desenvolvedora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_desenvolvedora VARCHAR(100) UNIQUE NOT NULL,
  site VARCHAR(255)
);

CREATE TABLE editoras (
  id_editora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_editora VARCHAR(100) UNIQUE NOT NULL,
  site VARCHAR(255)
);

CREATE TABLE jogos (
  id_jogo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  preco DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (preco >= 0),
  data_lancamento DATE NOT NULL,
  id_desenvolvedora INT NOT NULL,
  id_editora INT NOT NULL,
  url_imagem_capa VARCHAR(255),
  classificacao_media DECIMAL(3,1) NOT NULL DEFAULT 0 CHECK (classificacao_media BETWEEN 0 AND 10)
);

CREATE TABLE dlcs (
  id_dlc INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_jogo_base INT NOT NULL,
  titulo_dlc VARCHAR(255) NOT NULL,
  descricao_dlc TEXT NOT NULL,
  preco_dlc DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (preco_dlc >= 0),
  data_lancamento_dlc DATE NOT NULL
);

CREATE TABLE categorias (
  id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_categoria VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE promocoes (
  id_promocao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_promocao VARCHAR(100) NOT NULL,
  descricao TEXT NOT NULL,
  data_inicio TIMESTAMP NOT NULL,
  data_fim TIMESTAMP NOT NULL,
  tipo_desconto VARCHAR(20) NOT NULL,
  valor_desconto DECIMAL(5,2) NOT NULL CHECK (valor_desconto > 0)
);

CREATE TABLE noticias (
  id_noticia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  conteudo TEXT NOT NULL,
  data_publicacao TIMESTAMP NOT NULL,
  id_jogo_relacionado INT
);

CREATE TABLE compras (
  id_compra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INT NOT NULL,
  data_compra TIMESTAMP NOT NULL,
  valor_total DECIMAL(10,2) NOT NULL CHECK (valor_total >= 0),
  status_compra VARCHAR(20) NOT NULL
);

CREATE TABLE itens_compra (
  id_item_compra INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_compra INT NOT NULL,
  id_jogo INT,
  id_dlc INT,
  preco_unitario DECIMAL(10,2) NOT NULL CHECK (preco_unitario >= 0)
);

CREATE TABLE carrinhos_compra (
  id_carrinho INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INT UNIQUE NOT NULL,
  data_criacao TIMESTAMP NOT NULL,
  ultima_atualizacao TIMESTAMP NOT NULL
);

CREATE TABLE itens_carrinho (
  id_item_carrinho INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_carrinho INT NOT NULL,
  id_jogo INT,
  id_dlc INT,
  quantidade INT NOT NULL DEFAULT 1 CHECK (quantidade > 0),
  preco_no_carrinho DECIMAL(10,2) NOT NULL CHECK (preco_no_carrinho >= 0)
);


CREATE TABLE jogos_usuario (
  id_usuario INT,
  id_jogo INT,
  data_aquisicao TIMESTAMP NOT NULL,
  PRIMARY KEY (id_usuario, id_jogo)
);

CREATE TABLE avaliacoes_jogo (
  id_avaliacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INT NOT NULL,
  id_jogo INT NOT NULL,
  nota INT NOT NULL CHECK (nota BETWEEN 0 AND 10),
  comentario TEXT,
  data_avaliacao TIMESTAMP NOT NULL
);

CREATE TABLE jogo_categoria (
  id_jogo INT,
  id_categoria INT,
  PRIMARY KEY (id_jogo, id_categoria)
);

CREATE TABLE jogo_promocao (
  id_jogo INT,
  id_promocao INT,
  PRIMARY KEY (id_jogo, id_promocao)
);

CREATE TABLE requisitos_sistema (
  id_requisito INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_jogo INT UNIQUE NOT NULL,
  os VARCHAR(50) NOT NULL,
  processador VARCHAR(100) NOT NULL,
  memoria_ram VARCHAR(50) NOT NULL,
  placa_video VARCHAR(100) NOT NULL,
  armazenamento VARCHAR(50) NOT NULL,
  notas_adicionais TEXT
);

CREATE TABLE tickets_suporte (
  id_ticket INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INT NOT NULL,
  assunto VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  data_abertura TIMESTAMP NOT NULL,
  data_ultima_atualizacao TIMESTAMP NOT NULL,
  prioridade VARCHAR(20) NOT NULL
);

CREATE TABLE mensagens_ticket (
  id_mensagem INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_ticket INT NOT NULL,
  id_remetente INT NOT NULL,
  conteudo TEXT NOT NULL,
  data_envio TIMESTAMP NOT NULL
);

ALTER TABLE jogos
ADD CONSTRAINT fk_jogos_desenvolvedora FOREIGN KEY (id_desenvolvedora) REFERENCES desenvolvedoras (id_desenvolvedora),
ADD CONSTRAINT fk_jogos_editora FOREIGN KEY (id_editora) REFERENCES editoras (id_editora);

ALTER TABLE dlcs ADD CONSTRAINT fk_dlcs_jogo_base FOREIGN KEY (id_jogo_base) REFERENCES jogos (id_jogo);

ALTER TABLE jogo_categoria
ADD CONSTRAINT fk_jogocat_jogo FOREIGN KEY (id_jogo) REFERENCES jogos (id_jogo),
ADD CONSTRAINT fk_jogocat_categoria FOREIGN KEY (id_categoria) REFERENCES categorias (id_categoria);

ALTER TABLE compras ADD CONSTRAINT fk_compras_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE itens_compra
ADD CONSTRAINT fk_itenscompra_compra FOREIGN KEY (id_compra) REFERENCES compras (id_compra),
ADD CONSTRAINT fk_itenscompra_jogo FOREIGN KEY (id_jogo) REFERENCES jogos (id_jogo),
ADD CONSTRAINT fk_itenscompra_dlc FOREIGN KEY (id_dlc) REFERENCES dlcs (id_dlc);

ALTER TABLE jogos_usuario
ADD CONSTRAINT fk_jogos_usuario_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
ADD CONSTRAINT fk_jogos_usuario_jogo FOREIGN KEY (id_jogo) REFERENCES jogos (id_jogo);

ALTER TABLE avaliacoes_jogo 
ADD CONSTRAINT fk_avaliacoes_jogos_usuario FOREIGN KEY (id_usuario, id_jogo) REFERENCES jogos_usuario (id_usuario, id_jogo);

ALTER TABLE requisitos_sistema ADD CONSTRAINT fk_requisitos_jogo FOREIGN KEY (id_jogo) REFERENCES jogos (id_jogo);

ALTER TABLE jogo_promocao
ADD CONSTRAINT fk_jogopromo_jogo FOREIGN KEY (id_jogo) REFERENCES jogos (id_jogo),
ADD CONSTRAINT fk_jogopromo_promocao FOREIGN KEY (id_promocao) REFERENCES promocoes (id_promocao);

ALTER TABLE carrinhos_compra ADD CONSTRAINT fk_carrinho_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE itens_carrinho
ADD CONSTRAINT fk_itenscarrinho_carrinho FOREIGN KEY (id_carrinho) REFERENCES carrinhos_compra (id_carrinho),
ADD CONSTRAINT fk_itenscarrinho_jogo FOREIGN KEY (id_jogo) REFERENCES jogos (id_jogo),
ADD CONSTRAINT fk_itenscarrinho_dlc FOREIGN KEY (id_dlc) REFERENCES dlcs (id_dlc);

ALTER TABLE noticias ADD CONSTRAINT fk_noticias_jogo FOREIGN KEY (id_jogo_relacionado) REFERENCES jogos (id_jogo);

ALTER TABLE tickets_suporte ADD CONSTRAINT fk_tickets_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE mensagens_ticket
ADD CONSTRAINT fk_mensagens_ticket FOREIGN KEY (id_ticket) REFERENCES tickets_suporte (id_ticket),
ADD CONSTRAINT fk_mensagens_remetente FOREIGN KEY (id_remetente) REFERENCES usuarios (id_usuario);






